### PR TITLE
History manager

### PR DESCRIPTION
**Pull request by zumaad**
### notes about this PR:

This pull request does not change the behavior of the current code at all (the history manager is not hooked into the current event flow, but in my own repo I have hooked it in and verified that it works). I'm separating the profit tracker functionality into two PRs. This one, which doesn't affect existing functionality at all. And the next one (yet to come), where I will actually pass the trades to the HistoryManager residing in each FlippingItem. 

**None of these PRs have anything to do with the GUI.** 

This has code from https://github.com/Belieal/flipping-utilities/pull/13 in it so it makes the change look bigger.

The difference from https://github.com/Belieal/flipping-utilities/pull/13 is:

1. the OfferInfo class
2. the HistoryManager class
3. the addition of a history field In the FlippingItem class (this contains the HistoryManager) along with methods updateHistory(just calls HistoryManager.updatehistory) and currentProfit(just calls HistoryManager.currentProfit)
4. Passing in a HistoryManager to a FlippingItem on construction (this happens in FlippingPlugin)

difference 3 and 4 are self explanatory, so I'll only take a deep dive into 1 and 2.

### The OfferInfo class

This class is very simple. I wrote similar comments in the java doc but just to summarize again: Previously, whenever we got a GE update we turned the GrandExchangeOfferChanged to a GrandExchangeTrade and in doing so we lost access to two crucial pieces of information, the slot of the ge offer and its state. This was fine when we didn't need it. However, for profit tracking the slot is needed (**you can't figure out how much of an item was bought and sold if you have different slot data mixed in with each other as a trade only make sense within the context of its slot**) and the state is important for figuring how to respond to an event in the HistoryManager.

Now, I can't change a GrandExchangeTrade to include that information as that is runelite source code. I can't just make a new class unrelated to GrandExchangeTrade because many methods such as addFlipTrade, addToTradesList, and updateFlip expect a GrandExchangeTrade. Of course, I could change the code and make them accept the new class, but this would be a hassle because those methods also expect their input to have a certain api (certain methods) and I would have to recreate that with my new class. Instead, I opted for sub classing GrandExchangeTrade and adding the two new fields I needed. This way, my subclass would still be considered of type GrandExchangeTrade, thus not requiring a change in the method signatures of addFlipTrade, addToTradesList, and updateFlip. Additionally, it would inherit all the methods of GrandExchangeTrade, so now addFlipTrade, addToTradesList, and updateFlip could deal with their input in the same way.

So, previously in the method tradeConstructor we returned a grandExchangeTrade, now we still return a grandExchangeTrade but its a subclass called offerInfo with the same methods just a couple of new ones and two new fields :)

### The HistoryManager class

This is the class responsible for managing the history of a FlippingItem and returning valuable information such as the currentProfit of the item when queried.

It has two important methods: updateHistory and currentProfit.

**updateHistory:**

roughly speaking, updateHistory takes in an OfferInfo, sees what slot it came from, looks at the mapping of slot to slot history(slot history is a list of OfferInfo), takes the last OfferInfo in the list, and compares it the one it just got to see how much more of an item was just bought and sold. It then creates a new OfferInfo with the additional quantity bought/sold (current quantity - last seen quantity) and puts that newly constructed OfferInfo into a list called standardizedOffers. Of course, if that was the first offer for that slot, you can just add it to the standardizedOffers list as it already represents the quantity bought/sold from the last offer as the last offer didn't exist (quantity of 0, effectively).

A standardized offer is an offer that represents the new amount of an item bought/sold since the last offer. I do this "standardization" because this form of data is MUCH easier to work with. Just as a refresher (you know this already): the quantity we get in GE events represents the current quantity bought/sold overall in that trade, **NOT** the new quantity bought/sold since the last offer in that trade. So for example, as you are buying lobsters, you get one offer event with a quantity of 5 - this means you bought 5 lobsters. Then you get another offer event with a quantity of 7 - this means that overall in your trade you have bought 7 lobsters, **NOT** that you just bought an ADDITIONAL 7 lobsters.

**why is this "non standardized" data hard to work with?**
Because **A standardized offer has all the information needed to interpret it within itself**. A non standardized offer can **only** be interpreted within the context of the previous trades in that slot. Hint: (you may not have all the previous trades due to time screening and the solution is far messier than just standardizing the offers). 

### An example with non standardized offers:
Let's say for example we are buying lobsters - I don't actually flip lobsters :) - and we are getting buy offers from various slots. So, we get a buy offer from slot 1 with a quantity of 2, buy offer from slot 2 with a quantity of 3, buy offer from slot 1 with a quantity of 25, and a buy offer from slot 2 with a quantity of 10. So your offers list could look like this 
```[(slot:1, quantity 2), (slot:2, quantity 3), (slot:1, quantity:25), (slot:2, quantity:10)]```.

**How would you find out how many lobsters you bought?**
well thats easy! There are several ways: 

1. iterate through the list (ideally backwards) and find the last offer for a slot (this represents the quantity of lobsters bought in that slot at the current time), find the last offer for every slot and you have the quantity bought! (its more complicated than this because you could have a bunch of offers for a slot and than an offer that marks the completion of that trade and then a bunch more offers for that slot, from a new trade, and you would have to segregate based on that, which approach number 2 does beforehand)

2. Group the slots before hand and don't just have a flat list of all offers, have a list of lists, where each inner list represents a slot's history for one trade (from the first offer to the last offer which is either a bought, sold, cancelled buy, or cancelled sell). You could achieve this easily by having a map of slot to list of offers. When you see an offer for the slot just append to that slot's list. When you see an offer that marks the trade is complete, just add that slot's list to the list of lists and remove it from the hash map. With this list of lists, you can simply look at the last element in each of the inner lists and sum them up and that will be the quantity bought! so the list of lists in this case would look like:
```[ [(slot:1, quantity:2), (slot:1, quantity:25)], [(slot: 2, quantity: 3), (slot: 2, quantity: 10)]]```.

**BUT WAIT THERE IS A HUGE PROBLEM**: 
We allow users to find profits based on time. So what happens when you have to find profits for a certain window of time that doesn't include all the offers for a slot. Lets say for example a user wants their profit for the last 1 hour and just so happens that the first two trades happened 2 hours ago. So, in the last hour, these are the offers the came in. 
 ```[ (slot:1, quantity:25), (slot:2, quantity:10)]```, or (if you liked the nested lists approach,
something like this ```[ [(slot:1, quantity:25)], [(slot: 2, quantity: 10)]]```.

**Now, How many lobsters did you buy in the last hour?** 
You can't figure it out because the information you have (after filtering) only shows how much you have bought CURRENTLY, and since you don't know how many you bought before 1 hour ago, you don't know how many you bought in the past hour, as it's the difference in quantity of the last offer and the most recent offer that didn't make the time cutoff). 

In other words you need the whole history, **or at least you need the most recent offer that didn't make the cutoff**. In this case if you were calculating how many lobsters you bought in slot 1 in the last hour, you would need need the offer that didn't make the cutoff ```(slot:1, quantity:2)``` and the latest offer that made the cutoff
```(slot:1, quantity:25)```, then you could subtract 25-2 and figure out in the last hour you bought 23 lobsters!

**Finding the last offer that didn't make the cutoff is COMPLETELY POSSIBLE**. But, coding it is messy, far messier than simply standardizing the offers and sticking them in a list. Furthermore, standardizing the offers makes you not have to deal with lists of lists or messy algorithms for grouping the slot histories together (you can't just group based on slot as a slot can have multiple trades over a period of time, for example when you finish buying the lobsters and put in a new offer in that same slot for lobster).

### An example with standardization:
To show how simple it is with standardization, lets run the previous example with our standardized list.

Recall we got these events when buying lobsters: 
A buy offer from slot 1 with a quantity of 2, buy offer from slot 2 with a quantity of 3, buy offer from slot 1 with a quantity of 25, and a buy offer from slot 2 with a quantity of 10

Recall this was our unstandardized offer list
```[(slot:1, quantity 2), (slot:2, quantity 3), (slot:1, quantity:25), (slot:2, quantity:10)]```

our standardized offer list will look like this as every offer's quantity is subtracted by the last offer's (in that same slot) quantity :
```[(slot:1, quantity 2), (slot:2, quantity 3), (slot:1, quantity:23), (slot:2, quantity:7)]```

now lets say the user wants profit for the last hour, so we take away the first two offers that are 2 hours old and we get a list like:

```[(slot:1, quantity:23), (slot:2, quantity:7)]```

now we just iterate and sum :)

So thats why update history "standardizes" offers. And the standardization process is very simple, its described in the first paragraph under the "updateHistory" heading.

**currentProfit:**
the algorithm to get the profit with a standardized offer list is similar to the one I described in #6. Iterate through the standardized offer list, find the number of quantity of items bought and the quantity of items sold. Find the cost of the bought items and subtract it from the value of the sold items. The caveat is that the number of items sold and bought could be different. You can handle this by limiting the items you look for by the smallest of number of bought items and the number of sold items. So if you bought 10 items and only sold 5, return profit based on 5 buys and 5 sells. 
A simple sum of the buy and sell costs without accounting for the case where the number of items sold and bought are not equal could lead to really wonky profits (huge negative numbers if you haven't sold that dragon hunter lance you were flipping, etc). Thus this algorithm allows you to return "real time" profits and doesn't only work when you have sold off everything.

### CODE REVIEW

**Comment by Belieal** [comment]
Wow, this is amazingly well presented. I love the description of your thought process and I think your approach of standardized offer history is absolutely phenomenal! I really appreciate the effort you put into the documentation of your code as well. (Something I really need to work on!😌)

I'm wondering, would it be advantageous in terms of time complexity to recreate the ```slotHistory``` as an array of lists of ```OfferInfo``` with a size capacity of the amount of offer slots in total (6)? The offer slot id would then be connected to the index of the array instead of it having its own field. This means that all offerInfos are already sorted into their respective offer slots and could be added or retrieved by ```slotHistory.get/add(offerSlot - 1)```. This would improve complexity by not having to iterate through every single offer that has been made when trying to retrieve them. Although, I'm not 100% sure how big the history is really going to get for regular merchers, however I would assume collectors of huge amounts of items, who largely keep their offer slots open for weeks if not months at a time, could experience some delay while calculating the profits gained. Let me know what you think of this! :)

Lastly, I just wanted to get your opinion on making a new branch for working on this statistics tab, since I'm planning on sending the current master branch to review for Runelite as update v1.2. I think it would be appropriate to separate the two until the tab is finished. It would allow for us to more easily bugfix the current version of the plugin.

Again, thank you so much for the effort you put into this. I'll start working on the GUI (making the tab manager and general skeleton of the statistics UI), so we can start to visualize how this is all working!😄

**Comment by zumaad** [comment]
Thanks for the kind words, I really appreciate it :)

The time complexity of your approach is similar to mine I believe. Currently, the slotHistory is a hash map which maps slot to list of OfferInfo. All offerInfos are already sorted into their respective offer slots. So whenever I get a new event I can get the corresponding history for it by doing hashmap.get(slot). This is an O(1) operation, it's not iterating through the other slots- its just retrieving the data for that slot in the hash map. In fact, underlying the hash map is an array that enables this O(1) lookup, just like your idea. Your idea is still slightly better just because it's probably less overhead (a fixed size array vs a hashmap), but in terms of time complexity it should be the same.

The new branch sounds good!

Also, the widget feature is so good lol. Now when I flip I literally just put the item in, spam the widget (I made it subtract 1 from the selling price so it automatically undercuts :D) and hit enter. Its made flipping even less effort lmao.

**Comment by Belieal** [comment]
Right, well I need to read up on hash maps lmao

I've now made the branch, ```statistics-tab```, so if you could somehow change the PR to that I can merge it.

As for the widget, yeah I was pretty excited when I found out it was possible to change the input text. Infact, I want to make -/+ buttons but my god widgets are absolutely horrible to code. I think I ended up with about 150 lines of code just to add three textured buttons and it still didn't work!

**Comment by zumaad** [comment]
Changed the PR to target the statistics-tab branch

**Pull request merged**
