### PR TITLE
Hooked in History manager to the event pipeline, realtime profit, ge limit tracking, and limit refresh time tracking now works :)

### PR DESCRIPTION
**Pull request by zumaad**
The previous pr #19, involved the creation of the HistoryManager and the reimplementation of some algorithms for tracking ge limits and refresh times. 

This pr concerns actually hooking up the HistoryManager to the current event flow. While hooking it up I realized that lots of things were actually simplified and so I refactored a bunch of stuff.

**There isn't too much to explain, but I'll list the changes:**

### FlippingItem changes:
1. removed the tradehistory arraylist from FlippingItem, as this role is now occupied by the HistoryManager
2. removed remainingGeLimit field from FlippingItem and instead put in a method that queries the HistoryManager for the number of items bought in the current limit window and then I subtract that from the total ge limit. This method is called remainingGeLimit.
3. Removed @allArgsConstructor from flippingItem and made a constructor that takes in only an itemId, item name, and a totalGeLimit. latestBuyPrice, latestSellPrice, latestSellTime, latestBuyTime, are now set by a method in FlippingItem called updateMargin.  This is so that it's easy to see that only way those variables are being set is through one method, instead of through the method and the constructor initialization. This also makes the code shorter as updateMargin replaced some of the code in addToTradesList in FlippingPlugin as it used to get the margin and then pass it in to the FlippingItem constructor. Now I simply init the FlippingItem and then call FlippingItem.updateMargin(newOffer).
4. removed addTradeHistory as this is now the HistoryManager's role.
5. Removed updateGeLimitReset and replaced it with validateGeProperties and getGeLimitResetTime. validateGeProperties makes a call to the HistoryManager's validateGeProperties method, which just checks if the ge properties(num items you bought in the current window and the next ge limit refresh time) are outdated and if so, it resets them to zero and null, respectively. ```getGeLimitResetTime``` queries the HistoryManager for the nextGeLimitRefresh.

**new FlippingItem API:** FlippingItem now has a simplified constructor and has the following methods:
 ```updateHistory(OfferInfo newOffer)``` which takes in a OfferInfo and calls ```HistoryManager.updateHistory```. This updates the history which in turn is used to return accurate profit and ge limit/next refresh.

```remainingGeLimit() ```, which returns the ```totalGeLimit - HistoryManager.getItemsBoughtThisLimitWindow()```.

```getGeLimitResetTime()```, which returns the next time the ge limit will refresh by querying the HistoryManager like ```HistoryManager.getNextGeLimitRefresh()```.

```validateGeProperties()```, which calls HistoryManager.validateGeProperties(), which then resets ```nextGeLimitRefresh``` and ```itemsBoughtThisLimitWindow``` if the nextGeLimitRefresh has been passed.
(nextGeLimitRefresh and itemsBoughtThisLimitWindow are variables that are accessed by getters in ```remainingGeLimit()``` and ```getGeLimitResetTime()```

```updateMargin(OfferInfo newOffer)```, which takes in a new offer and updates the FlippingItems latestBuyPrice or latestSellPrice, and the latestSellTime or the latestBuyTime. As such, this is only invoked when an offer is a margin check.

```currentProfit(Instant earliestTime)```, which queries the HistoryManager and returns the current profit for that item.

### FlippingItemPanel changes:

not much here, just renamed some method names as I was trying to establish a clear difference between methods that updated the display and methods that actually changed the underlying data, as there were some methods that updated the display that sounded like they were doing the work of methods in FlippingItem.

1. renamed updateProfits to updatePotentialProfits, to differentiate it with the profit calculating logic of the HistoryManager, as potential profit Is just determined by margin*buy limit, which is different than actual profit as calculated by the HistoryManager.
2.  renamed updateGeLimits() to updateGePropertiesDisplay(), to make it clear that it only updates the display and doesn't change any state in the underlying FlippingItem.
3. renamed  checkOutdatedPriceTimes() to updatePriceOutdatedDisplay(), to make it clear that it only updates the display.

### FlippingPanel changes:

1.  renamed updateGELimit() to updateActivePanelsGePropertiesDisplay(), which is a mouthful so I'm open to changing It LOL. Once again though, I wanted to make it clear that this was a method that didn't change state at all.
2. Since I renamed method in FlippingItemPanel, I had to call them in the FlippingPanel by their renamed names, so I did.
3. changed updateTimes() to updateActivePanelsPriceOutdatedDisplay(), for the same reasons. I'm open to a shorter name once again.

### HistoryManager changes:
1. added validateGeProperties(), its discussed above, just checks if the refresh time is outdated, and if so, it resets it.
2. Some comments

### OfferInfo changes:
1. added a method called isMarginCheck, that determines whether this OfferInfo object is a margin check. Its cleaner than doing it on the outside and delegates responsibility to the OfferInfo class which is more appropriate cause its inspecting its own variables now.

### FlippingPlugin changes:
1. changed updateGELimitRemaining() to backgroundUpdateGePropertiesDisplay(), to make it clear that this is something that runs in the background constantly, and that it doesn't affect state, only the display.
2. made onGrandExchangeOfferChanged() a lot simpler. There are less branches to go through and each branch calls a distinct method.
3. made addToTradesList() a lot simpler. It just creates the new FlippingItem, calls FlippingItem.updateHistory(newOffer) and FlippingItem.updateMargin(newOffer) and adds it to the tradesList and thats it.
4. created updateFlippingItem(FlippingItem item, OfferInfo newOffer) which simply updates updates a FlippingItem using FlippingItem.updateHistory(newOffer) and FlippingItem.updateMargin(newOffer). This method also checks if the FlippingItem should be frozen according to the auto freeze config option.

That's it :)
I've been using it and it works

### CODE REVIEW

**Comment by Belieal** [comment]
Excellent! I just finished up the skeleton of the GUI and just need to hook things up, so this is great timing! :D

A little preview:
Panel

**Comment by zumaad** [comment]
That looks awesome, can't wait to try it out! There is one more thing we might have to change. When we currently hit clear, it deletes the tradesList and thus it would delete the profit. I flip on multiple accounts using the same client (use a diff account when I hit buy limits), so I hit clear every time I get on the new acc as I don't want to see the old stuff. But I still want to see the profit. I was wondering if perhaps we could also have a field for "old flipping items/non active flipping items", that we add to when a user hits clear. That way the trades list, and thus the display, gets cleared, but the we still have all the old data if we need it. So in a sense, the tradesList is just the items you are currently seeing (like activePanels).

**Comment by Belieal** [comment]
I was also wondering, could we use the RuneLite GE service to fetch past trades and use those for the profit calculation after a clear? I'm not super sure how fast it updates but it could be a good way to get old trades regardless if they were flipped with or without the plugin.

oh that reminds me, we don't support multi-account limit tracking. :D

**Comment by zumaad** [comment]
Hmm very interesting, I just checked out the geService. It looks pretty promising. It seems like it just stores it in a db, we would have to do some small massaging of the data as we would have to dump the standardized flipping offers of every flipping item that has been cleared into the db, but first we would have to convert it to a grandExchangeTrade. This is very easy as slot doesn't matter when an offer is standardized (slot is the data we lose when we convert an OfferInfo to a grandExchangeTrade).

Though this is easy, only slightly more difficult than storing it in memory in another field, I wonder if it's truly any better? My reasoning is that if a user wants to get the current profit and they have hit the reset button (thus the trades are no longer in the purview of the FlippingPlugin and are now in the database) or maybe they select a time thats pretty far back, further back then the oldest offer in the current trades list, we would have to fetch from the db.

The db has no way to intelligently query data based on time, so we would be have to fetch the data and then filter it, much like how we would have to do if the old data was stored in memory in a field of the flipping plugin.

However, if we can subclass grandExchangeService and add another ```get()``` and write our own SQL to get trades based on time, It could work.

Though, even if that works, I'm not entirely sure of the benefit other than the smaller memory footprint of the plugin (which may be a concern honestly, I have no clue) at increased complexity of dealing with a database(you would have to group trades based on item) as opposed to a list of flippingItems that you would just have to call currentProfit(time) on. 

Ultimately, the move over to a db that grandExchangeService uses wouldn't be difficult at all, but I'm not entirely sure what the benefit is.

It does sound cooler though :)

One benefit I can see is persistence even if the client is shut down. I don't know exactly how the current way we persist data is when a user shuts the client down (loadConfig()? I can't remember), but the db may be a more robust way of handling it.

**Comment by zumaad** [comment]
Oh, I just saw your comment about running the tests. If you are using IntelliJ to develop, you should see a green arrow next to the test class and every individual test case. You can click on the class level green arrow to run all the tests in the test class. Or you can click on a green arrow next to the method to run just that test. 

I also made a TestRunner class, that runs the tests in all the TestClasses specified. So, if we have many Test classes, you can just run the TestRunner class (there is a green arrow next to the class name) to run all of them.

**Comment by Belieal** [comment]
ooh, thank you! :D

**Pull request merged**
