### PR TITLE
misc

### PR DESCRIPTION
**Pull request by telans**
Add a .gitignore
Add newlines to files
Fix gradlew building, chmod u+x

### CODE REVIEW

**Comment by Belieal** [comment]
Hi there! I'm new to working with gradle, so would you explain what it is you want changed and why?

As for renaming the profit label, I think that's a much better way of conveying what it's trying to show. I'd love to merge it, but could you perhaps make it a separate PR? :)

**Comment by telans** [comment]
> Hi there! I'm new to working with gradle, so would you explain what it is you want changed and why?

Sure thing. I changed three things about 'gradlew':

1. I changed the permissions to make it user executable. (100644 → 100755)
2. All lines ended with "\r" as a windows artifact which doesn't play nice with linux (`/usr/bin/env: ‘sh\r’: No such file or directory`), so I fixed that with `dos2unix`. I would assume that's why the whole file looks like it's been replaced according to git.
3. Removed the explicit java location to let gradlew find java through $PATH. The version doesn't seem to matter, I managed to build this fine with openjdk 8 & 10 as well as 11.

I've force pushed the rename changes out and will create a new PR.

Cheers

**Comment by Belieal** [comment]
Gotcha, thanks for the explanation. :)

**Comment by Belieal** [comment]
Apologies, I had to revert these changes because the Runelite devs couldn't really work with it for some reason. However, I think this issue spans every plugin in the plugin hub as I've never touched it since forking it, so perhaps you should open an issue/pr on their repo?

**Pull request merged**
